# kubectl apply -k .
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: splunk
  template:
    metadata:
      labels:
        component: splunk
    spec:
      containers:
      #
      # Splunk from Docker Hub,
      # https://hub.docker.com/r/splunk/splunk/tags
      #
      # FWIW, the Splunk container runs Ansible on start!
      #
      - name: splunk
        # Appears to be based on "Debian GNU/Linux 10 (buster)":
        image: splunk/splunk:7.3.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        #
        # Splunk Free  provides no  authorization ---  allows password
        # free login  to everyone  on the network  [1]. You  have been
        # warned!
        #
        # [1] https://splunk.github.io/docker-splunk/advanced/LICENSE_INSTALL.html#splunk-free-license
        #
        # - name: "SPLUNK_LICENSE_URI"
        #   value: "Free"
        - name: "SPLUNK_START_ARGS"
          value: "--accept-license"
        # Only for  Trial license.  Password  must contain at  least 8
        # total printable ASCII characters.
        - name: "SPLUNK_PASSWORD"
          value: "abc12345"
---
apiVersion: v1
kind: Service
metadata:
  name: splunk
spec:
  type: ClusterIP
  selector:
    component: splunk
  ports:
  - port: 8000
    targetPort: 8000
---
#
# We assume here that all of *.localhost resolve to the local machine:
#
#     http://splunk.localhost
#     https://splunk.localhost
#
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: splunk.localhost
    http:
      paths:
      - backend:
          serviceName: splunk
          servicePort: 8000
